name: Daily Auto News

on:
  schedule:
    # 1. 아침 배달: 한국 시간 오전 6시 (서버 지연 대비해 UTC 21:00로 설정)
    - cron: '0 21 * * *'
    
    # 2. 오후 배달: 한국 시간 오후 1시 30분으로 예약 (UTC 04:30)
    # 서버가 1~2시간 늦게 작동해도 오후 3시 전후에는 도착합니다.
    - cron: '30 4 * * *'

    
  workflow_dispatch: # 직접 실행 버튼

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: pip install feedparser requests

      - name: Run Script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          USER_ID: ${{ secrets.USER_ID }}
        run: python main.py
